### ISSUE TITLE
Shared and consistent data

### ISSUE THREAD

**Issue by lukeconibear** [wrfchem-leeds/python-scripts#5]
Following the WRFChem technical meeting on 13/07/2020, it was suggested that it would be useful to have surface measurements/satellite observations in standard format in a shared location for these python scripts to work with and for users to share data.

A suitable location would be `/nobackup/WRFChem` on ARC4.

The data type I presume would be NetCDF4, but this should have standardised formatting in relation to the python scripts which use them?

The data hosted here could include:
- MODIS AOD
- Air quality measurements:
    - OpenAQ (Global, India, etc.)
    - China

Please, suggest other data that would be useful here or a standardised format type.

Help for this work is welcome.

**Comment by bjsilver** [comment]
Hi Luke, could you send a path or the output from ncdump -h to the data you have downloaded from OpenAQ? I think it would be a good idea to use whatever format these netcdfs are in, as then any future data from openaq can be easily shared. I can convert my China data to this format and then I can add it to the arc4 nobackup. 

Do you think it is better to share cleaned data or the original raw data? For the China data I remove repeated data and anomalies. If I share the cleaned data it should probably come with a record of what was done to it.

**Comment by lukeconibear** [comment]
Well the OpenAQ stores its data as multiple `.ndjson.gz` files per day. I then converted these JSON files into pandas dataframes (found in here `/nobackup/WRFChem/openaq/csv/`) and set the datetime as the index. The formatting was already done well, as shown below. Scripts for this are [here](https://github.com/lukeconibear/openaq) if you want to see. I suppose you could create a netcdf file for these, though it wasn't the obvious choice to me as the data isn't on a normal lat-lon grid.

![image](https://user-images.githubusercontent.com/19871268/87658254-da7c1780-c753-11ea-9d9b-9ea39ee10f58.png)

Another option is to convert measurements, such as your China data, into similar dataframes.

Maybe both the cleaned and raw data, so users have the option of getting straight to the analysis or to doing their own custom data pre-processing. Yes, that a good idea to have the cleaning steps documented with the cleaned data.

**Comment by bjsilver** [comment]
Hi Luke,

It could be nice to have a lookup table (and a script that makes it by iterating through the measurement data). That way we can write comparison scripts that could automatically find all the measurements inside the domain from the lookup table that would contain all the coordinates. We can keep the metadata in the measurement csvs as well. 

We could have a structure like `/nobackup/WRFChem/measurements/` that contains the lookup table and the directories with the separate measurement datasets. Then in the lookup table, one column could be the name of the directory that contains that dataset, as well as the file name.

Do you think that makes sense?

**Comment by lukeconibear** [comment]
Okay, sure. That sounds like a nice idea to allow users to automatically find all the local observations for their domain. If you don't have write access to `/nobackup/WRFChem`, then Helen should be able to enable that for you.

**Comment by lukeconibear** [comment]
In case this is helpful, the script I used to convert your netcdf files for China to a single tidy pandas dataframe is [here](https://github.com/wrfchem-leeds/python-scripts/blob/master/china-netcdf_to_df-tidy.ipynb), (table example below). This was for the 2014-2018 data and I've copied the file over to `/nobackup/WRFChem/measurements/df_china_measurements_2014-2018_tidy.csv`.

![image](https://user-images.githubusercontent.com/19871268/87695227-24cabc00-c787-11ea-9286-b9e887ce775d.png)

**Comment by lukeconibear** [comment]
Let's just go with the format of the OpenAQ data as the template, as this is likely to be a key source of measurements going forward.

The summary of the format is:
- 1 Pandas DataFrame per year (if < 30 GB, otherwise split into chunks)
- Datetime in UTC as the index
- 1 row per observation of a parameter
- Parameters are lower case e.g. `['pm25', 'o3', 'pm10', 'co', 'no2', 'so2']`
- Columns to include `['date.utc', 'city', 'unit', 'value', 'country', 'location', 'parameter', 'sourceName', 'sourceType', 'date.local', 'coordinates.latitude', 'coordinates.longitude', 'averagingPeriod.unit', 'averagingPeriod.value']`

I've converted the updated China measurements to this format using this script [here](https://nbviewer.jupyter.org/github/lukeconibear/openaq/blob/master/convert_df_to_openaq_formatting.ipynb).

An example of the DataFrame is below:
![image](https://user-images.githubusercontent.com/19871268/111624271-619df580-87e3-11eb-811e-7b64fc200604.png)
